public with sharing class Constants {
     
    public static final String PROFILE_SYS_ADMIN = 'System Administrator';
    public static final String ADMIN_PERMISSION = 'Blackthorn_Base_Admin';
    public static final String PAYMENT_ADMIN_PERMISSION = 'Blackthorn_Base_Admin';
    public static final String EVENT_ADMIN_PERMISSION = 'Blackthorn_Base_Admin';
    public static final String STOREFRONT_ADMIN_PERMISSION = 'Blackthorn_Base_Admin';

    public static final String BASE_PACKAGE_ID = '03361000000DksxAAC';
    public static final String PAYMENT_PACKAGE_ID = '03361000000DksxAAC'; //THIS IS A CONSTANT VALUE SHOULD NOT BE CHANGED
    public static final String EVENT_PACKAGE_ID = '03361000000DksxAAC';
    public static final String STOREFRONT_PACKAGE_ID = '03361000000DksxAAC';

    public static final String BASE_NAMESPACE = 'bt_base';
    
}