name: Salesforce Package Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install CumulusCI
        run: pip install cumulusci
        
      - name: Connect Org
        run: |
          cci org connect packageorg

      - name: Convert to Metadata API Format
        run: |
          cci task run dx_convert_from

      - name: Deploy to Package Org
        run: |
          cci task run deploy --org packageorg

      - name: Determine Release Type
        id: release-type
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ "beta" ]]; then
            echo "beta"
          else
            echo "major"
          fi
        continue-on-error: true

      - name: Create Beta Release
        if: steps.release-type.outputs.release-type == 'beta'
        run: |
          cci task run upload_beta --org packageorg

      - name: Create Major Release
        if: steps.release-type.outputs.release-type == 'major'
        run: |
          cci task run upload_production --org packageorg