name: Salesforce Package Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install CumulusCI
        run: pip install cumulusci

      - name: Debug Secrets and cumulusci.key
        run: |
          echo "Contents of cumulusci.key:"
          cat cumulusci.key

          echo "Resolved PACKAGE_ORG_USERNAME: ${{ secrets.PACKAGE_ORG_USERNAME }}"
          echo "Resolved PACKAGE_ORG_PASSWORD: ${{ secrets.PACKAGE_ORG_PASSWORD }}"

      - name: Connect Org
        run: |
          cci org connect packageorg

      - name: Convert to Metadata API Format
        run: |
          cci task run dx_convert_from

      - name: Deploy to Package Org
        run: |
          cci task run deploy --org packageorg

      - name: Determine Release Type
        id: release-type
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ "beta" ]]; then
            echo "beta"
          else
            echo "major"
          fi
        continue-on-error: true

      - name: Create Beta Release
        if: steps.release-type.outputs.release-type == 'beta'
        run: |
          cci task run upload_beta --org packageorg

      - name: Create Major Release
        if: steps.release-type.outputs.release-type == 'major'
        run: |
          cci task run upload_production --org packageorg